services:
  flutter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flutter_web
    ports:
      - "3000:80"
    networks:
      - rotafy_network

networks:
  rotafy_network:
    external: true  