server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Flutter Web (SPA) — redireciona tudo pro index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy pras chamadas de API pro Laravel
    location /api/ {
        proxy_pass http://laravel_app:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}